export const CREATE_CONTACT = "CREATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const CHECK_ALL = "CHECK_ALL";
export const AFTER_DELETE_ALL = "AFTER_DELETE_ALL";
export const DELETE_ALL = "DELETE_ALL";
export const DELETE_ONE_CONTACT = "DELETE_ONE_CONTACT";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
